version: '2'
services:
  golang:
    image: golang
    volumes:
      - './src:/go/src/github.com/blacknikka/go-client-mock'
    tty: true
    working_dir: /go/src/github.com/blacknikka/go-client-mock
    ports:
      - '5000:5000'
  json:
    image: clue/json-server
    ports:
      - '80:80'
    volumes:
      - './db.json:/data/db.json'
  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - './grafana:/var/lib/grafana'
  influx:
    build: ./docker/influx
    ports:
      - '8086:8086'
    volumes:
      - './influx/db:/var/lib/influxdb'
      - './influx/influxdb.conf:/etc/influxdb/influxdb.conf'
  telegraf:
    image: telegraf
    depends_on:
      - influx
    volumes:
      - './telegraf/telegraf.conf:/etc/telegraf/telegraf.conf'


