version: '2'
services:
  golang:
    image: golang
    volumes:
      - '.:/go/src/github.com/blacknikka/go-client-mock'
    tty: true
    working_dir: /go/src/github.com/blacknikka/go-client-mock
  json:
    image: clue/json-server
    ports:
      - '80:80'
    volumes:
      - './db.json:/data/db.json'
